sudo: true
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      env: TARGET=linux
    - os: linux
      env: TARGET=windows
      services:
        - docker
    - os: osx
      env: TARGET=osx

install:
  - .travis/install-$TARGET

script:
  - source .travis/env-$TARGET.sh
  - RUN $CMAKE -B_build -H. -DCMAKE_INSTALL_PREFIX:PATH=$PWD/_install
  - RUN $MAKE -C _build -j4 -k install

branches:
  only:
    - master
