sudo: true
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      env: ENV=linux
    - os: linux
      env: ENV=windows
      services:
        - docker
    - os: osx
      env: ENV=osx

install:
  - .travis/install-$ENV
  - . .travis/env-$ENV.sh
  - git clone --depth=1 https://github.com/iphydf/toxcore
  - RUN $CMAKE -Btoxcore/_build -Htoxcore -DLOGGING=ON -DDEBUG=ON -DCMAKE_INSTALL_PREFIX:PATH=$CURDIR/libs
  - RUN $MAKE -C toxcore/_build -j$NPROC -k install

script:
  - RUN $CMAKE -B_build -H. -DCMAKE_INSTALL_PREFIX:PATH=$CURDIR/_install
  - RUN $MAKE -C _build -j$NPROC -k install
  - .travis/git-deploy

branches:
  only:
    - master
