#!/bin/sh

set -e -x

brew install libvpx opus libsodium

git clone https://github.com/TokTok/toxcore ../toxcore
cd ../toxcore
autoreconf -fi
./configure
make -j4
make install

brew update > /dev/null
brew install ffmpeg qrencode qt5 sqlcipher
