#!/bin/sh

set -e -x

DOCKER_IMAGE=iphydf/windows-x86-qt5

docker pull $DOCKER_IMAGE
docker run --rm $DOCKER_IMAGE > dockcross
chmod +x dockcross

test -d toxcore || git clone --depth=1 https://github.com/TokTok/toxcore
./dockcross sh -c '
cd toxcore && \
  autoreconf -fi && \
  ./configure \
    --prefix=/work/libs \
    --host=i686-w64-mingw32.static \
    --enable-static \
    --disable-shared && \
  make install -j4'
